#!/bin/bash

# Mesh Bridge Port Configuration Script
# This script helps configure the bridge server port during installation

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default less commonly used ports
DEFAULT_PORTS=(8888 9080 7080 8765 9090 7777)

echo -e "${BLUE}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Mesh Bridge - Port Configuration                ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to check if a port is available
check_port() {
    local port=$1
    if command -v nc &> /dev/null; then
        ! nc -z localhost "$port" 2>/dev/null
        return $?
    elif command -v lsof &> /dev/null; then
        ! lsof -i :"$port" &> /dev/null
        return $?
    else
        # Fallback: assume port is available
        return 0
    fi
}

# Function to find first available port from defaults
find_available_port() {
    for port in "${DEFAULT_PORTS[@]}"; do
        if check_port "$port"; then
            echo "$port"
            return 0
        fi
    done
    # If all defaults are taken, return first default
    echo "${DEFAULT_PORTS[0]}"
}

# Find best available port
RECOMMENDED_PORT=$(find_available_port)

echo -e "${GREEN}Recommended port (automatically selected): ${RECOMMENDED_PORT}${NC}"
echo ""
echo "This port is less commonly used and should avoid conflicts with:"
echo "  • Port 8080 (common HTTP alternate)"
echo "  • Port 8081 (often used by proxies)"
echo "  • Port 3000 (common dev servers)"
echo "  • Port 5173 (Vite dev server)"
echo ""
echo -e "${YELLOW}Available options:${NC}"
echo "  1) Use recommended port (${RECOMMENDED_PORT})"
echo "  2) Choose from other less common ports"
echo "  3) Enter a custom port"
echo ""

read -p "Select option [1-3] (default: 1): " choice
choice=${choice:-1}

case $choice in
    1)
        SELECTED_PORT=$RECOMMENDED_PORT
        ;;
    2)
        echo ""
        echo "Less commonly used ports:"
        for i in "${!DEFAULT_PORTS[@]}"; do
            port="${DEFAULT_PORTS[$i]}"
            if check_port "$port"; then
                echo -e "  $((i+1))) Port ${port} ${GREEN}(available)${NC}"
            else
                echo -e "  $((i+1))) Port ${port} ${RED}(in use)${NC}"
            fi
        done
        echo ""
        read -p "Select port number [1-${#DEFAULT_PORTS[@]}]: " port_choice
        SELECTED_PORT="${DEFAULT_PORTS[$((port_choice-1))]}"
        ;;
    3)
        read -p "Enter custom port (1024-65535): " SELECTED_PORT
        # Validate port range
        if [ "$SELECTED_PORT" -lt 1024 ] || [ "$SELECTED_PORT" -gt 65535 ]; then
            echo -e "${RED}Error: Port must be between 1024 and 65535${NC}"
            exit 1
        fi
        ;;
    *)
        echo -e "${RED}Invalid option${NC}"
        exit 1
        ;;
esac

# Verify port is not in use
if ! check_port "$SELECTED_PORT"; then
    echo -e "${YELLOW}Warning: Port ${SELECTED_PORT} appears to be in use${NC}"
    read -p "Continue anyway? [y/N]: " continue_choice
    if [[ ! "$continue_choice" =~ ^[Yy]$ ]]; then
        echo "Port configuration cancelled"
        exit 1
    fi
fi

echo ""
echo -e "${GREEN}✓ Selected port: ${SELECTED_PORT}${NC}"
echo ""

# Create .env file
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
    # Backup existing .env
    cp "$ENV_FILE" "${ENV_FILE}.backup"
    echo -e "${YELLOW}Backed up existing .env to .env.backup${NC}"
fi

# Write port to .env
cat > "$ENV_FILE" << EOF
# Mesh Bridge Configuration
# Generated by configure-port.sh on $(date)

# Bridge server port (default: 8888)
BRIDGE_PORT=${SELECTED_PORT}

# Auto-connect to radios on startup
AUTO_CONNECT=true
EOF

echo -e "${GREEN}✓ Configuration saved to ${ENV_FILE}${NC}"
echo ""
echo -e "${BLUE}Port configuration complete!${NC}"
echo ""
echo "The bridge server will run on port ${SELECTED_PORT}"
echo ""
echo "To start the bridge server:"
echo -e "  ${YELLOW}npm run bridge${NC}"
echo ""
echo "Access the UI at:"
echo -e "  ${YELLOW}http://localhost:${SELECTED_PORT}${NC}"
echo ""
echo "To reconfigure the port, run this script again:"
echo -e "  ${YELLOW}bash scripts/configure-port.sh${NC}"
echo ""
