#!/bin/bash

# Mesh Bridge Production Installation Script
# This script installs Mesh Bridge as a systemd service for production use

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Mesh Bridge - Production Installation           ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo -e "${RED}Error: Do not run this script as root${NC}"
    echo "Run as your normal user - the script will prompt for sudo when needed"
    exit 1
fi

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"

echo -e "${GREEN}Project directory: ${PROJECT_DIR}${NC}"
echo ""

# Step 1: Check Node.js version
echo -e "${BLUE}[1/8]${NC} Checking Node.js installation..."
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    exit 1
fi

NODE_VERSION=$(node -v)
echo -e "${GREEN}✓ Node.js ${NODE_VERSION} found${NC}"
echo ""

# Step 2: Install dependencies
echo -e "${BLUE}[2/8]${NC} Installing dependencies..."
cd "$PROJECT_DIR"
if [ ! -d "node_modules" ]; then
    npm install
else
    echo -e "${YELLOW}Dependencies already installed, skipping...${NC}"
fi
echo ""

# Step 3: Configure port
echo -e "${BLUE}[3/8]${NC} Configuring bridge server port..."
if [ -f "$PROJECT_DIR/scripts/configure-port.sh" ]; then
    bash "$PROJECT_DIR/scripts/configure-port.sh"
else
    echo -e "${YELLOW}Port configuration script not found, using default port 8888${NC}"
    cat > "$PROJECT_DIR/.env" << 'ENVEOF'
# Mesh Bridge Configuration
# Generated by install.sh

# Bridge server port (default: 8888)
BRIDGE_PORT=8888

# Auto-connect to radios on startup
AUTO_CONNECT=true
ENVEOF
fi
echo ""

# Step 4: Build production frontend
echo -e "${BLUE}[4/8]${NC} Building production frontend..."
npm run build
echo -e "${GREEN}✓ Production build complete${NC}"
echo ""

# Step 5: Create systemd service file
echo -e "${BLUE}[5/8]${NC} Creating systemd service..."

# Get the Node.js binary path
NODE_PATH=$(which node)
USER_NAME=$(whoami)
USER_HOME=$(eval echo ~$USER_NAME)

cat > "$PROJECT_DIR/mesh-bridge.service" << SERVICEEOF
[Unit]
Description=Meshtastic Bridge Server
Documentation=https://github.com/IceNet-01/Mesh-Bridge
After=network.target

[Service]
Type=simple
User=${USER_NAME}
WorkingDirectory=${PROJECT_DIR}
Environment="NODE_ENV=production"
Environment="PATH=${PATH}"
ExecStart=${NODE_PATH} bridge-server/index.mjs
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=mesh-bridge

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=${PROJECT_DIR}
ReadWritePaths=/run/user/$(id -u)

# Allow access to serial devices
SupplementaryGroups=dialout
DeviceAllow=/dev/ttyACM0 rw
DeviceAllow=/dev/ttyACM1 rw
DeviceAllow=/dev/ttyACM2 rw
DeviceAllow=/dev/ttyACM3 rw
DeviceAllow=/dev/ttyUSB0 rw
DeviceAllow=/dev/ttyUSB1 rw
DeviceAllow=/dev/ttyUSB2 rw
DeviceAllow=/dev/ttyUSB3 rw

[Install]
WantedBy=multi-user.target
SERVICEEOF

echo -e "${GREEN}✓ Service file created${NC}"
echo ""

# Step 6: Install systemd service
echo -e "${BLUE}[6/8]${NC} Installing systemd service..."
sudo cp "$PROJECT_DIR/mesh-bridge.service" /etc/systemd/system/
sudo systemctl daemon-reload
echo -e "${GREEN}✓ Service installed${NC}"
echo ""

# Step 7: Enable service to start on boot
echo -e "${BLUE}[7/8]${NC} Enabling service to start on boot..."
sudo systemctl enable mesh-bridge.service
echo -e "${GREEN}✓ Service enabled${NC}"
echo ""

# Step 8: Start the service
echo -e "${BLUE}[8/8]${NC} Starting Mesh Bridge service..."
sudo systemctl start mesh-bridge.service
sleep 3

# Check service status
if sudo systemctl is-active --quiet mesh-bridge.service; then
    echo -e "${GREEN}✓ Mesh Bridge service is running!${NC}"
    echo ""
    
    # Get the configured port
    BRIDGE_PORT=$(grep BRIDGE_PORT "$PROJECT_DIR/.env" | cut -d '=' -f2 | tr -d ' ')
    BRIDGE_PORT=${BRIDGE_PORT:-8888}
    
    echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║           Installation Complete!                     ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${GREEN}Access the Mesh Bridge UI at:${NC}"
    echo -e "  ${YELLOW}http://localhost:${BRIDGE_PORT}${NC}"
    echo ""
    echo -e "${GREEN}Useful commands:${NC}"
    echo -e "  View logs:       ${YELLOW}sudo journalctl -u mesh-bridge.service -f${NC}"
    echo -e "  Service status:  ${YELLOW}sudo systemctl status mesh-bridge.service${NC}"
    echo -e "  Restart service: ${YELLOW}sudo systemctl restart mesh-bridge.service${NC}"
    echo -e "  Stop service:    ${YELLOW}sudo systemctl stop mesh-bridge.service${NC}"
    echo -e "  Disable service: ${YELLOW}sudo systemctl disable mesh-bridge.service${NC}"
    echo ""
    echo -e "${GREEN}The service will automatically start on boot.${NC}"
    echo ""
else
    echo -e "${RED}✗ Service failed to start${NC}"
    echo ""
    echo "Check the logs for details:"
    echo -e "  ${YELLOW}sudo journalctl -u mesh-bridge.service -n 50${NC}"
    exit 1
fi
